#include "buzzer.h"

#include "config.h"

void playBlockedAlert() {
  TONE_IF_NOT_MUTED(BUZZER_PIN, BLOCKED_BEEP_FIRST_HZ, BEEP_DURATION_MS);
  delay(LOOP_DELAY_MS);
  TONE_IF_NOT_MUTED(BUZZER_PIN, BLOCKED_BEEP_SECOND_HZ, BEEP_DURATION_MS);
}

void playMenuEnterSound() {
  TONE_IF_NOT_MUTED(BUZZER_PIN, MENU_ENTER_BEEP_FIRST_HZ, BEEP_DURATION_MS);
  delay(LOOP_DELAY_MS);
  TONE_IF_NOT_MUTED(BUZZER_PIN, MENU_ENTER_BEEP_SECOND_HZ, BEEP_DURATION_MS);
}

void playMenuExitSound() {
  TONE_IF_NOT_MUTED(BUZZER_PIN, MENU_EXIT_BEEP_HZ, BEEP_DURATION_MS);
}

void playResetConfirmSound() {
  TONE_IF_NOT_MUTED(BUZZER_PIN, RESET_BEEP_FIRST_HZ, BEEP_DURATION_MS);
  delay(LOOP_DELAY_MS);
  TONE_IF_NOT_MUTED(BUZZER_PIN, RESET_BEEP_SECOND_HZ, BEEP_DURATION_MS);
}

void playClickSound() {
  TONE_IF_NOT_MUTED(BUZZER_PIN, CLICK_BEEP_HZ, CLICK_DURATION_MS);
}

void playLockedSound() {
  TONE_IF_NOT_MUTED(BUZZER_PIN, LOCKED_BEEP_HZ, BEEP_DURATION_MS * 3);
}
